[project]
name = "drain"
version = "0.1.0"
description = "Dashboard for Dozzle"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "plotly>=6.5.0",
    "polars>=1.36.1",
    "pyarrow>=22.0.0",  # Override streamlit's constraint
    "ruff>=0.14.9",
    "streamlit>=1.52.1",
    "watchdog>=6.0.0",
]


[tool.basedpyright]
reportUnusedCallResult = "none"
