[project]
name = "drain"
version = "0.1.0"
description = "Dashboard for Dozzle"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = [
    "plotly>=6.3.1",
    "polars>=1.35.1",
    "ruff>=0.14.3",
    "streamlit>=1.51.0",
    "watchdog>=6.0.0",
]


[tool.basedpyright]
reportUnusedCallResult = "none"
