[project]
name = "drain"
version = "0.1.0"
description = "Dashboard for Dozzle"
readme = "README.md"
requires-python = ">=3.14.3"
dependencies = [
    "plotly>=6.5.2",
    "polars>=1.38.1",
    "pyarrow>=22.0.0",  # Override streamlit's constraint
    "ruff>=0.15.0",
    "streamlit>=1.54.0",
    "watchdog>=6.0.0",
]


[tool.basedpyright]
reportUnusedCallResult = "none"
