[project]
name = "drain"
version = "0.1.0"
description = "Dashboard for Dozzle"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = [
    "plotly>=6.4.0",
    "polars>=1.35.2",
    "ruff>=0.14.5",
    "streamlit>=1.51.0",
    "watchdog>=6.0.0",
]


[tool.basedpyright]
reportUnusedCallResult = "none"
